# Generated by Django 5.0 on 2026-09-12 12:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institution_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('elementary school', 'Elementary School'), ('junior high school', 'Junior High School'), ('high school', 'High School'), ('university', 'University')], default='', max_length=50)),
                ('thumbnail', models.URLField(blank=True, default='')),
                ('year_started', models.IntegerField()),
                ('year_ended', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
