# Generated by Django 5.0 on 2026-09-22 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='category',
            field=models.CharField(choices=[('elementary school', 'Elementary School'), ('junior high school', 'Junior High School'), ('high school', 'High School'), ('university', 'University')], default='university', max_length=50),
        ),
    ]
